### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by IFoxuk** [MCBEPluginModer/PermissionsEx#2]
Чат в Энде работает некорректно, выводит `prefix% player% suffix% message%`, в зависимости от форматирования.
Глобальный чат игнорирует суффиксы, префиксы миров, использует общий префикс и суффикс.
Перм `chatmanager.chat.magic` крашит.

**Comment by IFoxuk** [comment]
Большая буква "Ч" определяется как цветосимвол.
Ведра не заполняются водой/лавой, но при это убирают блок воды/лавы.

**Comment by IFoxuk** [comment]
`pex user group remove` не отбирает группу игрока, хотя вывод сообщения есть.

**Comment by MCBEPluginModer** [comment]
> Большая буква "Ч" определяется как цветосимвол.
> Ведра не заполняются водой/лавой, но при это убирают блок воды/лавы.

так команда право отбирает,а не группу)

**Comment by IFoxuk** [comment]
> > Большая буква "Ч" определяется как цветосимвол.
> > Ведра не заполняются водой/лавой, но при это убирают блок воды/лавы.
> 
> так команда право отбирает,а не группу)

Так право забирает `/pex user remove`, а не `/pex user group remove`

**Comment by MCBEPluginModer** [comment]
Всё пофикшено
